### ISSUE TITLE
(Question) Roadmap and plan

### ISSUE THREAD

**Issue by BonfaceKilz** [AfricanDigitalAssetFramework/kweli#2]
Is there any roadmap and contribution guidelines for the project? How would a new developer contribute to the project outside reading the white paper?

**Comment by DibbsZA** [comment]
Yes. I too am interested.

**Comment by ShelbySolomonDarnell** [comment]
Not yet at a point to accept code contributions. We will ask for such at earliest Q2 2020.

**Comment by BonfaceKilz** [comment]
Oh ok. I'm going ahead to close this then :+1:
